version: 2
project_name: goecs

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy -v

builds:
  # Linux AMD64 with CGO
  - id: linux-amd64-cgo
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_CFLAGS=-O2 -static -fno-stack-protector -Wl,--gc-sections
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0 -extldflags=-static
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/amd64 (CGO)"
      post:
        - echo "Successfully built linux/amd64 (CGO)"
        - echo "---"

  # Linux 386 with CGO
  - id: linux-386-cgo
    env:
      - CGO_ENABLED=1
      - CC=gcc -m32
      - CGO_CFLAGS=-m32 -static -O1 -march=i686 -mtune=generic -fno-stack-protector
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0 -extldflags=-static
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - 386
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/386 (CGO)"
      post:
        - echo "Successfully built linux/386 (CGO)"
        - echo "---"

  # Linux ARM64 with CGO
  - id: linux-arm64-cgo
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-gcc
      - CGO_CFLAGS=-static -O1 -fno-stack-protector
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0 -extldflags=-static
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - arm64
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/arm64 (CGO)"
      post:
        - echo "Successfully built linux/arm64 (CGO)"
        - echo "---"

  # Windows AMD64 with CGO
  - id: windows-amd64-cgo
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CGO_CFLAGS=-O2 -static -static-libgcc -static-libstdc++
      - CGO_LDFLAGS=-static -static-libgcc -static-libstdc++
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0 -extldflags=-static
    flags:
      - -trimpath
    goos:
      - windows
    goarch:
      - amd64
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for windows/amd64 (CGO)"
      post:
        - echo "Successfully built windows/amd64 (CGO)"
        - echo "---"

  # Windows 386 with CGO
  - id: windows-386-cgo
    env:
      - CGO_ENABLED=1
      - CC=gcc-mingw-w64-i686
      - CGO_CFLAGS=-O2 -static -static-libgcc -static-libstdc++
      - CGO_LDFLAGS=-static -static-libgcc -static-libstdc++
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0 -extldflags=-static
    flags:
      - -trimpath
    goos:
      - windows
    goarch:
      - 386
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for windows/386 (CGO)"
      post:
        - echo "Successfully built windows/386 (CGO)"
        - echo "---"

  # Darwin AMD64 with CGO
  - id: darwin-amd64-cgo
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_CFLAGS=-O2 -arch x86_64 -mmacosx-version-min=10.12
      - CGO_LDFLAGS=-arch x86_64 -mmacosx-version-min=10.12
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
    flags:
      - -trimpath
    goos:
      - darwin
    goarch:
      - amd64
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for darwin/amd64 (CGO)"
        - echo "Checking osxcross tools..."
        - which o64-clang || echo "o64-clang not found"
        - which o64-clang++ || echo "o64-clang++ not found"
      post:
        - echo "Successfully built darwin/amd64 (CGO)"
        - echo "---"

  # Darwin ARM64 with CGO
  - id: darwin-arm64-cgo
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
      - CGO_CFLAGS=-O2 -arch arm64 -mmacosx-version-min=11.0
      - CGO_LDFLAGS=-arch arm64 -mmacosx-version-min=11.0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
    flags:
      - -trimpath
    goos:
      - darwin
    goarch:
      - arm64
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for darwin/arm64 (CGO)"
        - echo "Checking osxcross tools..."
        - which oa64-clang || echo "oa64-clang not found"
        - which oa64-clang++ || echo "oa64-clang++ not found"
      post:
        - echo "Successfully built darwin/arm64 (CGO)"
        - echo "---"

  # Linux RISC-V 64 with CGO
  - id: linux-riscv64-cgo
    env:
      - CGO_ENABLED=1
      - CC=riscv64-linux-gnu-gcc
      - CGO_CFLAGS=-static -O1 -fno-stack-protector
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0 -extldflags=-static
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - riscv64
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/riscv64 (CGO)"
      post:
        - echo "Successfully built linux/riscv64 (CGO)"
        - echo "---"

  # Linux MIPS64 with CGO
  - id: linux-mips64-cgo
    env:
      - CGO_ENABLED=1
      - CC=mips64-linux-gnuabi64-gcc
      - CGO_CFLAGS=-static -O1 -fno-stack-protector
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0 -extldflags=-static
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - mips64
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/mips64 (CGO)"
      post:
        - echo "Successfully built linux/mips64 (CGO)"
        - echo "---"

  # Linux MIPS64LE with CGO
  - id: linux-mips64le-cgo
    env:
      - CGO_ENABLED=1
      - CC=mips64el-linux-gnuabi64-gcc
      - CGO_CFLAGS=-static -O1 -fno-stack-protector
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0 -extldflags=-static
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - mips64le
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/mips64le (CGO)"
      post:
        - echo "Successfully built linux/mips64le (CGO)"
        - echo "---"

  # Linux PPC64LE with CGO
  - id: linux-ppc64le-cgo
    env:
      - CGO_ENABLED=1
      - CC=powerpc64le-linux-gnu-gcc
      - CGO_CFLAGS=-static -O1 -fno-stack-protector
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0 -extldflags=-static
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - ppc64le
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/ppc64le (CGO)"
      post:
        - echo "Successfully built linux/ppc64le (CGO)"
        - echo "---"

  # Linux ARM (no CGO)
  - id: linux-arm-nocgo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "5"
      - "6"
      - "7"
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/arm (no CGO)"
      post:
        - echo "Successfully built linux/arm (no CGO)"
        - echo "---"

  # Linux S390X (no CGO)
  - id: linux-s390x-nocgo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - s390x
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/s390x (no CGO)"
      post:
        - echo "Successfully built linux/s390x (no CGO)"
        - echo "---"

  # Linux MIPS (no CGO)
  - id: linux-mips-nocgo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - mips
    gomips:
      - softfloat
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/mips (no CGO)"
      post:
        - echo "Successfully built linux/mips (no CGO)"
        - echo "---"

  # Linux MIPSLE (no CGO)
  - id: linux-mipsle-nocgo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - mipsle
    gomips:
      - softfloat
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/mipsle (no CGO)"
      post:
        - echo "Successfully built linux/mipsle (no CGO)"
        - echo "---"

  # Linux PPC64 (no CGO)
  - id: linux-ppc64-nocgo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - ppc64
    main: ./
    binary: goecs
    no_unique_dist_dir: true
    hooks:
      pre:
        - echo "Starting build for linux/ppc64 (no CGO)"
      post:
        - echo "Successfully built linux/ppc64 (no CGO)"
        - echo "---"

  # # FreeBSD AMD64 (no CGO)
  # - id: freebsd-amd64-nocgo
  #   env:
  #     - CGO_ENABLED=0
  #   ldflags:
  #     - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
  #   flags:
  #     - -trimpath
  #   goos:
  #     - freebsd
  #   goarch:
  #     - amd64
  #   main: ./
  #   binary: goecs
  #   no_unique_dist_dir: true
  #   hooks:
  #     pre:
  #       - echo "Starting build for freebsd/amd64 (no CGO)"
  #     post:
  #       - echo "Successfully built freebsd/amd64 (no CGO)"
  #       - echo "---"

  # # FreeBSD ARM64 (no CGO)
  # - id: freebsd-arm64-nocgo
  #   env:
  #     - CGO_ENABLED=0
  #   ldflags:
  #     - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}} -checklinkname=0
  #   flags:
  #     - -trimpath
  #   goos:
  #     - freebsd
  #   goarch:
  #     - arm64
  #   main: ./
  #   binary: goecs
  #   no_unique_dist_dir: true
  #   hooks:
  #     pre:
  #       - echo "Starting build for freebsd/arm64 (no CGO)"
  #     post:
  #       - echo "Successfully built freebsd/arm64 (no CGO)"
  #       - echo "---"

universal_binaries:
  - name_template: "goecs"
    replace: false
    ids:
      - darwin-amd64-cgo
      - darwin-arm64-cgo

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
  disable: false
  ids:
    - linux-amd64-cgo
    - linux-386-cgo
    - linux-arm64-cgo
    - linux-riscv64-cgo
    - linux-mips64-cgo
    - linux-mips64le-cgo
    - linux-ppc64le-cgo
    - windows-amd64-cgo
    - windows-386-cgo
    - darwin-amd64-cgo
    - darwin-arm64-cgo
    - linux-arm-nocgo
    - linux-s390x-nocgo
    - linux-mips-nocgo
    - linux-mipsle-nocgo
    - linux-ppc64-nocgo
    # - freebsd-amd64-nocgo
    # - freebsd-arm64-nocgo
  extra_files:
    - glob: "./goecs.sh"

snapshot:
  name_template: "goecs"

archives:
  - id: default
    name_template: "goecs_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
    allow_different_binary_count: true
    builds:
      - linux-amd64-cgo
      - linux-386-cgo
      - linux-arm64-cgo
      - linux-riscv64-cgo
      - linux-mips64-cgo
      - linux-mips64le-cgo
      - linux-ppc64le-cgo
      - windows-amd64-cgo
      - windows-386-cgo
      - darwin-amd64-cgo
      - darwin-arm64-cgo
      - linux-arm-nocgo
      - linux-s390x-nocgo
      - linux-mips-nocgo
      - linux-mipsle-nocgo
      - linux-ppc64-nocgo
      # - freebsd-amd64-nocgo
      # - freebsd-arm64-nocgo

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - New translations