name: goreleaser

on:
  workflow_dispatch:
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container:
      # 1.20 是 Windows 7/8 Server 2008/2012 最后一个支持版本
      image: goreleaser/goreleaser-cross:v1.20
    steps:
      - run: |
          git config --global --add safe.directory /__w/ecs/ecs
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Configure Git for Private Modules
        run: |
          git config --global url."https://${{ secrets.GHT }}@github.com/".insteadOf "https://github.com/"
          git config --global url."git@github.com:".insteadOf "https://github.com/"
        env:
          GITHUB_TOKEN: ${{ secrets.GHT }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GHT }}
          GOPRIVATE: github.com/oneclickvirt/security

      - name: Update goecs.sh with new version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          FILE="goecs.sh"
          BRANCH="master"
          # Checkout master branch
          git fetch origin $BRANCH:$BRANCH
          git switch $BRANCH
          # Replace version in goecs.sh
          sed -i "s/\(_yellow \"Unable to get version info, using default version \).*\(\".*\)/\1$VERSION\2/" "$FILE"
          sed -i "s/\(ECS_VERSION=\"\).*\(\"\)/\1$VERSION\2/" "$FILE"
          # Commit and push
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "$FILE"
          git commit -m "chore: update ECS_VERSION to $VERSION in goecs.sh"
          git push origin $BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GHT }}

